# Generated by Django 5.2 on 2025-04-30 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('nr_sali', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('oddzial', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dozymetr',
            fields=[
                ('IDdozymetru', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('data_ostatniej_kalibracji', models.DateField()),
                ('status', models.CharField(choices=[('aktywny', 'Aktywny'), ('wycofany', 'Wycofany'), ('w_naprawie', 'W naprawie'), ('zutylizowany', 'Zutylizowany')], max_length=12)),
                ('typ', models.CharField(max_length=50)),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dozymetry', to='mojaapka.osoba')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dozymetry', to='mojaapka.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Sprzet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('rok_produkcji', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('numer_ref', models.CharField(max_length=50, unique=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprzety', to='mojaapka.sala')),
            ],
        ),
    ]
