# Generated by Django 5.2 on 2025-05-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mojaapka', '0001_initial'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='dozymetr',
        #     old_name='data_ostatniej_kalibracji',
        #     new_name='data_ostatniej_kontroli',
        # ),
        migrations.RenameField(
            model_name='sprzet',
            old_name='rok_produkcji',
            new_name='rok_zakupu',
        ),
        migrations.AddField(
            model_name='sprzet',
            name='data_ostatniego_przegladu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sprzet',
            name='numer_kontaktowy_serwis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sprzet',
            name='numer_seryjny',
            field=models.CharField(default='brak', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprzet',
            name='producent_model',
            field=models.CharField(default='brak', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprzet',
            name='promieniujacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sprzet',
            name='status',
            field=models.CharField(choices=[('aktywne', 'Aktywne'), ('w_naprawie', 'W naprawie'), ('wycofane', 'Wycofane'), ('uszkodzone', 'Uszkodzone')], default='aktywne', max_length=20),
        ),
        migrations.AddField(
            model_name='sprzet',
            name='typ_sprzetu',
            field=models.CharField(choices=[('RTG', 'Aparat RTG'), ('TK', 'Tomograf komputerowy'), ('USG', 'Ultrasonograf'), ('INNE', 'Inne')], default='brak', max_length=50),
            preserve_default=False,
        ),
    ]
