# Generated by Django 5.2 on 2025-05-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mojaapka', '0002_rename_data_ostatniej_kalibracji_dozymetr_data_ostatniej_kontroli_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dozymetr',
            old_name='data_ostatniej_kalibracji',
            new_name='data_ostatniej_kontroli',
        ),
        migrations.RenameField(
            model_name='sprzet',
            old_name='nazwa',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='sprzet',
            old_name='producent_model',
            new_name='producent',
        ),
        migrations.RemoveField(
            model_name='sprzet',
            name='numer_ref',
        ),
        migrations.AlterField(
            model_name='sprzet',
            name='rok_zakupu',
            field=models.CharField(default='brak', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sprzet',
            name='sala',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sprzet',
            name='typ_sprzetu',
            field=models.CharField(choices=[('RTG', 'Aparat RTG'), ('TK', 'Tomograf komputerowy'), ('USG', 'Ultrasonograf'), ('PET', 'PET'), ('SPECT', 'SPECT'), ('MRI', 'Rezonans magnetyczny'), ('CID', 'Detektor promieniowania jonizującego'), ('GAUGE', 'Miernik promieniowania'), ('INNE', 'Inne')], max_length=50),
        ),
    ]
