# Generated by Django 5.2 on 2025-05-16 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mojaapka', '0003_rename_data_ostatniej_kalibracji_dozymetr_data_ostatniej_kontroli_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprzet',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mojaapka.sala'),
        ),
    ]
